version: '3.8'

services:
  smoke:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        pip install -r requirements.txt &&
        python -c 'import src; print(\"✅ Package imports successfully\")' &&
        pytest tests/test_basic.py -v &&
        echo \"✅ Smoke test completed successfully\"
      "
    environment:
      - PYTHONPATH=/app 